/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiPresignRouteImport } from './routes/api.presign'
import { Route as ApiMoveRouteImport } from './routes/api.move'
import { Route as ApiListRouteImport } from './routes/api.list'
import { Route as ApiDownloadFolderRouteImport } from './routes/api.download-folder'
import { Route as ApiDeleteRouteImport } from './routes/api.delete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresignRoute = ApiPresignRouteImport.update({
  id: '/api/presign',
  path: '/api/presign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoveRoute = ApiMoveRouteImport.update({
  id: '/api/move',
  path: '/api/move',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListRoute = ApiListRouteImport.update({
  id: '/api/list',
  path: '/api/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadFolderRoute = ApiDownloadFolderRouteImport.update({
  id: '/api/download-folder',
  path: '/api/download-folder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteRoute = ApiDeleteRouteImport.update({
  id: '/api/delete',
  path: '/api/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/delete': typeof ApiDeleteRoute
  '/api/download-folder': typeof ApiDownloadFolderRoute
  '/api/list': typeof ApiListRoute
  '/api/move': typeof ApiMoveRoute
  '/api/presign': typeof ApiPresignRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/delete': typeof ApiDeleteRoute
  '/api/download-folder': typeof ApiDownloadFolderRoute
  '/api/list': typeof ApiListRoute
  '/api/move': typeof ApiMoveRoute
  '/api/presign': typeof ApiPresignRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/delete': typeof ApiDeleteRoute
  '/api/download-folder': typeof ApiDownloadFolderRoute
  '/api/list': typeof ApiListRoute
  '/api/move': typeof ApiMoveRoute
  '/api/presign': typeof ApiPresignRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/delete'
    | '/api/download-folder'
    | '/api/list'
    | '/api/move'
    | '/api/presign'
    | '/api/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/delete'
    | '/api/download-folder'
    | '/api/list'
    | '/api/move'
    | '/api/presign'
    | '/api/upload'
  id:
    | '__root__'
    | '/'
    | '/api/delete'
    | '/api/download-folder'
    | '/api/list'
    | '/api/move'
    | '/api/presign'
    | '/api/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDeleteRoute: typeof ApiDeleteRoute
  ApiDownloadFolderRoute: typeof ApiDownloadFolderRoute
  ApiListRoute: typeof ApiListRoute
  ApiMoveRoute: typeof ApiMoveRoute
  ApiPresignRoute: typeof ApiPresignRoute
  ApiUploadRoute: typeof ApiUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presign': {
      id: '/api/presign'
      path: '/api/presign'
      fullPath: '/api/presign'
      preLoaderRoute: typeof ApiPresignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/move': {
      id: '/api/move'
      path: '/api/move'
      fullPath: '/api/move'
      preLoaderRoute: typeof ApiMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/list': {
      id: '/api/list'
      path: '/api/list'
      fullPath: '/api/list'
      preLoaderRoute: typeof ApiListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-folder': {
      id: '/api/download-folder'
      path: '/api/download-folder'
      fullPath: '/api/download-folder'
      preLoaderRoute: typeof ApiDownloadFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete': {
      id: '/api/delete'
      path: '/api/delete'
      fullPath: '/api/delete'
      preLoaderRoute: typeof ApiDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDeleteRoute: ApiDeleteRoute,
  ApiDownloadFolderRoute: ApiDownloadFolderRoute,
  ApiListRoute: ApiListRoute,
  ApiMoveRoute: ApiMoveRoute,
  ApiPresignRoute: ApiPresignRoute,
  ApiUploadRoute: ApiUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
